// <auto-generated />
using System;
using Log2Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Log2Server.Migrations
{
    [DbContext(typeof(DbLsContext))]
    [Migration("20221013084710_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Log2Server.Models.LsApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("char(32)")
                        .HasColumnName("app_key")
                        .IsFixedLength(true)
                        .HasComment("键");

                    b.Property<string>("AppSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("app_secret")
                        .IsFixedLength(true)
                        .HasComment("密钥");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("创建时间");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppKey" }, "APP_KEY_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "CreateAt" }, "CREATE_AT_INDEX");

                    b.ToTable("ls_app");
                });
#pragma warning restore 612, 618
        }
    }
}
